CREATE TABLE KhachHang
(
    MaKH number NOT NULL,
    Ho varchar2(10) NOT NULL,
    Ten varchar2(20) NOT NULL,
    NgaySinh date NOT NULL,
    GioiTinh varchar2(10) NOT NULL,
    LoaiKH varchar2(15) DEFAULT 'Than thiet',
    username varchar2(30) not null unique,
    password varchar2(30) not null,
    tichluy number default 0,
    CONSTRAINT PK_KH PRIMARY KEY(MaKH)
);

ALTER SESSION SET NLS_DATE_FORMAT ='DD/MM/YYYY HH24:MI:SS';
CREATE SEQUENCE MaKH_seq1 START WITH 1;
INSERT INTO KHACHHANG(MAKH,HO,TEN,NGAYSINH,GIOITINH,USERNAME,PASSWORD) VALUES (MaKH_seq1.nextval,'TRAN','VAN NHU Y','16/04/1991','Nam','nhuy1999','nhuy123');
INSERT INTO KHACHHANG(MAKH,HO,TEN,NGAYSINH,GIOITINH,USERNAME,PASSWORD) VALUES (MaKH_seq1.nextval,'LE','THI TRUC HOA','02/09/1999','Nu','truchoa1999','duyphuong123');
INSERT INTO KHACHHANG(MAKH,HO,TEN,NGAYSINH,GIOITINH,USERNAME,PASSWORD) VALUES (MaKH_seq1.nextval,'HOANG','THUY TRINH','05/01/1999','Nu','thuytrinh1999','thuytrinh123');
INSERT INTO KHACHHANG(MAKH,HO,TEN,NGAYSINH,GIOITINH,USERNAME,PASSWORD) VALUES (MaKH_seq1.nextval,'PHAM','NHAT TUAN','01/01/1999','Nam','nhattuan1999','nhattuan123');
SELECT * FROM KHACHHANG

CREATE SEQUENCE MaNV_seq2 START WITH 1;